# Generated by Django 5.2 on 2025-04-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categroy',
            new_name='category',
        ),
    ]
